FNRouter help
=============

// File router

Консольная утилита по перекладыванию файлов по каталогам и отправке на почту.

Работает на Windows 2000/XP/Vista/7. Установка не требуется. 

Требуется установленный http://www.microsoft.com/downloads/ru-ru/details.aspx?displaylang=ru&FamilyID=9cfb2d51-5ff4-4491-b0e5-b386f32c0992[.NET framework] версии 2.0 или выше

Распространяется по лицензии http://www.gnu.org/licenses/gpl-3.0.html[GNU GPL 3]

[red]#ВАЖНО!!! ВЫ ИСПОЛЬЗУЕТЕ ДАННЫЙ ПРОГРАММНЫЙ ПРОДУКТ НА СВОЙ СТРАХ И РИСК!!!#

*Автор заранее слагает с себя ответственность за весь возможный ущерб, причиненный программой.*

*This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.*

Описание
--------
Это консольная утилита, позволяет автоматизировать процесс раскладывания файлов по каталогам и отправке их на почту.

Настраивается через файл с правилами (по умолчанию fnrouter.ini) (кодировка win1251)

Параметры запуска: 

------------------------
fnrouter.exe [-cfile:Имя_файла_с_правилами] -rule:имя_правила
------------------------

Где имя_правила: имя правила для обработки

Если имя файла с правилами не указано используется fnrouter.ini

Одновременный запуск одного и того же правила блокируется (разные могут исполнятся одновременно).

Формат файла правил
-------------------

Строка после символа  # (решетка) - считается коментарием и не обрабатвается

Каждая строка задает одно действие и записывается в виде:

-----------------------
rule=имя_правила; act=действие; s=источник; d=приемник; contain=строка_в_файле; 
-----------------------

Точка с запятой (;) обязательна и обозначает окончание параметра.

Каждое правило может состоять из нескольких строк. Действия при этом выполняются сверху вниз

Действиями (act) могут быть:

Copy::
 копировать
Move::
 переместить
Send::
 отправить файл по почте
SendMsg::
 отправить уведомление на почту, без отправки самого файла
RunWait::
 запустить внешнюю программу с ожиданием
RunNoWait::
 запустиь внешнюю программу без ожидания
UnRar::
 распаковать архив rar

Действие выполняется над файлами указанными в источнике (s). Это полный путь к каталогу и маска файла. Например:

---------------------------------
rule=test; act=Copy;  s=d:\temp\0\*; d=d:\temp\1; 
---------------------------------
Скопирует все файлы из d:\temp\0\ в d:\temp\1

Дополнительно можно указывать, что файл должен содержать заданную строку параметром contain=строка; (Сравнение регистрозависимое)

В имени каталогов можно указывать дату/время в %. Например %yyMMdd% - преобразуется в текущую дату. Т.е. что-то вроде d:\temp\%yyMMdd%\1\*

Для RunWait и RunNoWait испльзуется параметр cmd=имя_запускаемого_файла.
Файл запускается если в источнике есть указанные файлы.
----------------------------
rule=имя_правила; act=RunWait; s=d:\temp\*.*; cmd=c:\balalaika.exe; 
----------------------------

Для указания параметров почтового сервера используется специальное правило:
----------------------------
rule=settings; mailsrv=почтовый_сервер; mailfrom=адрес отправителя; mailport=номер_порта; mailuser=имя пользователя;  mailpass=пароль; 
----------------------------

Эту строку можно указывать несколько раз, соответственно для последующих строк будут менятся значения (например можно поменять только mailfrom).
Или в строку ипользующую отправку можно добавлять соответствующие параметры, тогда они перекроют глобальные значения (только для этой строки, последующие строки будут использовать настройки правила settings)
mailuser, mailpass, mailport можно не указывать.

Для отправки файла на почту:
-------------------------------
rule=имя_правила;  act=Send;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------
В теме и тексте можно использовать Переменные вроде  %FileName% - имя файла, %FullFileName% - полное имя файла, см. ниже

Для отправки уведомления о файлах на почту:

-------------------------------
rule=имя_правила;  act=SendMsg;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------

Для распаковки Rar
-------------------------------
rule=имя_правила; act=UnRar;  s=d:\test\in\*.rar; d=E:\test\%FileWithoutExt%; 
-------------------------------
%FileWithoutExt% - создаст каталог с именем архива (без расширения)
Rar.exe - должен находится в каталоге с программой.

В теме и тексте письма, при указании путей можно использовать следующие переменные:

%ListFileName%::
 список коротких имен файлов (только для почты, список через запятую)
%ListFullFileName%::
 список длинных имен файлов (только для почты, список через запятую)
%FullFileName%::
 полное имя файла
%FileName%::
 короткое имя файла
%FileWithoutExt%::
 только имя файла без расширения
%ExtFile%::
 расширение имени файла

Так же можно использовать переменные для текущей даты/времени (в именах каталогов и письмах). См. приложение.

Во время работы ведутся логи. Запись идет в подкаталог Log программы. Файлы логов имеют имя ГГММДД-имя_правила.log - каждый файл соответсвует одному дню одного правила.

Контакты 
--------

Вопросы, предложения, замечания принимаются по адресу atsave@narod.ru  +  
Сайт программы: http://atsave.narod.ru