FNRouter 0.1.7
==============

// File router

Консольная утилита по перекладыванию файлов по каталогам и отправке на почту.

Работает на Windows 2000/XP/Vista/7. Установка не требуется. 

Требуется установленный http://www.microsoft.com/downloads/ru-ru/details.aspx?displaylang=ru&FamilyID=9cfb2d51-5ff4-4491-b0e5-b386f32c0992[.NET framework] версии 2.0 или выше

Распространяется по лицензии http://www.gnu.org/licenses/gpl-3.0.html[GNU GPL 3]

[red]#ВАЖНО!!! ВЫ ИСПОЛЬЗУЕТЕ ДАННЫЙ ПРОГРАММНЫЙ ПРОДУКТ НА СВОЙ СТРАХ И РИСК!!!#

*Автор заранее слагает с себя ответственность за весь возможный ущерб, причиненный программой.*

*This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.*

Описание
--------
Это консольная утилита, позволяет автоматизировать процесс раскладывания файлов по каталогам и отправке их на почту.

Настраивается через файл с правилами (по умолчанию fnrouter.ini) (кодировка win1251)

Параметры запуска: 

------------------------
fnrouter.exe [-cfile:Имя_файла_с_правилами] -rule:имя_правила
------------------------

Где имя_правила: имя правила для обработки

Если имя файла с правилами не указано используется fnrouter.ini

Одновременный запуск одного и того же правила блокируется (разные могут исполнятся одновременно).

Формат файла правил
-------------------

Строка после символа  # (решетка) - считается коментарием и не обрабатвается

Каждая строка задает одно действие и записывается в виде:

-----------------------
Имя_параметра1=значение_параметра1; Имя_параметра2=значение_параметра2; Имя_параметра3=значение_параметра3; ...
-----------------------

Точка с запятой (;) обязательна и обозначает окончание параметра.

Параметры правила
-----------------

Rule::
  Обязателен. Имя правила. Может быть одинаковым для нескольких строчек. При запуске программы указывается имя правила, строчки имеющие это имя будут последовательно обрабатываться сверху вниз. Каждое правило может состоять из нескольких строк. Действия при этом выполняются сверху вниз
Act::
	Обязателен. Действие выполняемое с файлами.
S::
	Обязателен. Полный путь к каталогу с обрабатываемыми файлами. Если не используется параметр Inc, то должен содержать маску (только одну). Подкаталоги не обрабатываются. Если используется параметр Inc, маска не указывается. Может содержать переменные даты времени/имен файлов
Inc::
	Не обязательный параметр. Маски включаемых файлов для обработки, разделяются запятыми (,).
Exclude::
	Не обязательный параметр. Маски исключаемых из обработки файлов, разделяются запятыми (,).
Contain::
	Не обязательный параметр. Строка которую должен содержать файл. Сравнение регистрозависимое.
D::
	Полный путь к каталогу назанчения. Используется не во всех действиях. Может содержать переменные даты времени/имен файлов.
Cmd::
	Файл для запуска. Используется в командах запуска внешнего файла
Subj::
	Тема письма. Для правил отправки почты. Может содержать переменные даты времени/имен файлов.
Text::
	Текст письма. Для правил отправки почты. Может содержать переменные даты времени/имен файлов.

Для указания параметров почтового сервера используются параметры:
	
mailsrv::
	почтовый сервер
mailfrom::
	адрес отправителя
mailport::
	номер порта
mailuser::
	имя пользователя
mailpass::
	пароль


Действия
--------

Действиями (Act) могут быть:

Copy::
 копировать
Move::
 переместить
Send::
 отправить файл по почте
SendMsg::
 отправить уведомление на почту, без отправки самого файла
RunWait::
 запустить внешнюю программу с ожиданием
RunNoWait::
 запустиь внешнюю программу без ожидания
UnRar::
 распаковать архив rar
UnArj::
 распаковать архив arj
UnCab::
 распаковать архив cab
PbGen::
 сформировать квитки PB1 для налоговой
	* d - Каталог для квитков
MergeNalogFile::
 Объеденить файлы налоговой в один убрав подпись после строки ===
	* d - имя объединенного файла
	* pages=yes - можно указать для разбивки на страницы
 

Отбор файлов для обработки
--------------------------
 
Действие выполняется над файлами попадающими в условия отбора. Если необходимо отобрать файлы только по одной маске, то достаточно указать полный путь к каталогу и маску в параметре s

Например:

---------------------------------
rule=test; act=Copy;  s=d:\temp\0\*; d=d:\temp\1; 
---------------------------------
Скопирует все файлы из d:\temp\0\ в d:\temp\1

Возможно указание нескольких масок файлов для включения в обработку параметром Inc. Маски разделяютя запятой ",". При этом в параметре s необходимо указывать только полный путь к каталогу.

Например:

---------------------------------
rule=test; act=Copy;  s=d:\temp\0; d=d:\temp\1; Inc=*.rar,*.zip; 
---------------------------------
Скопирует все файлы rar и zip из d:\temp\0\ в d:\temp\1

Возможно указание масок файлов для исключения из обработки параметром Exclude. Маски разделяютя запятой ","

Например:

---------------------------------
rule=test; act=Copy;  s=d:\temp\0; d=d:\temp\1; Inc=*.rar,*.zip; Exclude=temp.rar,temp.zip;
---------------------------------

Скопирует все файлы rar и zip кроме temp.rar и temp.zip из d:\temp\0\ в d:\temp\1

Дополнительно можно указывать, что файл должен содержать заданную строку параметром contain=строка; (Сравнение регистрозависимое)

В имени каталогов можно указывать дату/время в %. Например %yyMMdd% - преобразуется в текущую дату. Т.е. что-то вроде d:\temp\%yyMMdd%\1\*



Файловые операции
-----------------

Если необходимо скопировать файлы из каталога в несколько каталогов, то можно использовать несколько строчек подряд

Например:

---------------------------------
rule=test; act=Copy;  s=d:\temp\0\*; d=d:\temp\1; 
rule=test; act=Move;  s=d:\temp\0\*; d=d:\temp\backup\%yyMMdd%; 
---------------------------------

Такой же принцип используется для разбора из одного каталога разных типов файлов по разным каталогам

---------------------------------
# Архивы направо
rule=test; act=Copy;  s=d:\temp\0\*.rar; d=d:\temp\Arh; 
# Тексты налево
rule=test; act=Copy;  s=d:\temp\0\*.txt; d=d:\temp\txt; 
# Доки на почту
rule=test; act=Send;  s=d:\temp\0\*.doc; to=me@mail.com; subj=Файлы; text=%FileName%;
# И все в архив
rule=test; act=Move;  s=d:\temp\0\*; d=d:\temp\backup\%yyMMdd%;
---------------------------------



Указание параметров отправки почты
----------------------------------

Для указания параметров почтового сервера используется специальное правило:
----------------------------
rule=settings; mailsrv=почтовый_сервер; mailfrom=адрес отправителя; mailport=номер_порта; mailuser=имя пользователя;  mailpass=пароль; 
----------------------------

Эту строку можно указывать несколько раз, соответственно для последующих строк будут менятся значения (например можно поменять только mailfrom).
Или в строку ипользующую отправку можно добавлять соответствующие параметры, тогда они перекроют глобальные значения (только для этой строки, последующие строки будут использовать настройки правила settings)
mailuser, mailpass, mailport можно не указывать.

Отправка писем
--------------

Для отправки файла на почту:
-------------------------------
rule=имя_правила;  act=Send;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------
В теме и тексте можно использовать Переменные вроде  %FileName% - имя файла, %FullFileName% - полное имя файла, см. ниже

Для отправки уведомления о файлах на почту:

-------------------------------
rule=имя_правила;  act=SendMsg;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------



Так же можно использовать переменные для текущей даты/времени (в именах каталогов и письмах). См. приложение.

Распаковка архивов
------------------

Для распаковки Rar
-------------------------------
rule=имя_правила; act=UnRar;  s=d:\test\in\*.rar; d=E:\test\%FileWithoutExt%; 
-------------------------------
%FileWithoutExt% - создаст каталог с именем архива (без расширения) + 
Rar.exe - должен находится в путях %Path% или в каталоге с программой.

Для распаковки Arj
-------------------------------
rule=имя_правила; act=UnArj;  s=d:\test\in\*.arj; d=E:\test\%yyMMdd%; 
-------------------------------
arj32.exe - должен находится в путях %Path% или в каталоге с программой.

Для распаковки Cab
-------------------------------
rule=имя_правила; act=UnCab;  s=d:\test\in\*; d=E:\test\%yyMMdd%; 
-------------------------------
expand.exe - должен находится в путях %Path% или в каталоге с программой. Обычно находится в %WinDir%\System32

Запуск внешних программ
-----------------------

Используйте действия RunWait и RunNoWait

Для RunWait и RunNoWait испльзуется параметр cmd=имя_запускаемого_файла.

Файл запускается если существуют файлы попадающие в критерии отбора.

----------------------------
rule=имя_правила; act=RunWait; s=d:\temp\*; cmd=c:\balalaika.exe; 
----------------------------

Запустится c:\balalaika.exe если в каталоге d:\temp есть файлы

Протоколы работы
----------------

Во время работы ведутся логи. Запись идет в подкаталог Log программы. Файлы логов имеют имя ГГММДД-имя_правила.log - каждый файл соответсвует одному дню одного правила.

Контакты 
--------

Вопросы, предложения, замечания принимаются по адресу atsave@narod.ru  +  
Сайт программы: http://atsave.narod.ru

Приложение
----------

В теме и тексте письма, при указании путей можно использовать следующие переменные:

%ListFileName%::
 список коротких имен файлов (только для почты, список через запятую)
%ListFullFileName%::
 список длинных имен файлов (только для почты, список через запятую)
%FullFileName%::
 полное имя файла
%FileName%::
 короткое имя файла
%FileWithoutExt%::
 только имя файла без расширения
%ExtFile%::
 расширение имени файла

Допустимые символы заключаемые в знак "%", для преобразования в текущую дату/время в имени каталогов. Остальные символы останутся без преобразования. 


"d"::
 День месяца, в диапазоне от 1 до 31.  +   
 6/1/2009 1:45:30 PM -> 1  +  
 6/15/2009 1:45:30 PM -> 15

"dd"::	
 День месяца, в диапазоне от 01 до 31.  +  
 6/1/2009 1:45:30 PM -> 01  +  
 6/15/2009 1:45:30 PM -> 15

"ddd"::
Сокращенное название дня недели.  +  
6/15/2009 1:45:30 PM -> Mon (en-US)  +  
6/15/2009 1:45:30 PM -> Пн (ru-RU)  +  
6/15/2009 1:45:30 PM -> lun. (fr-FR)

"dddd"::	
Полное название дня недели.  +  
6/15/2009 1:45:30 PM -> Monday (en-US)  +  
6/15/2009 1:45:30 PM -> понедельник (ru-RU)  +  
6/15/2009 1:45:30 PM -> lundi (fr-FR)

"f"::	
Десятые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 6  +  
6/15/2009 13:45:30.050 -> 0 

"ff"::	
Сотые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 61  +  
6/15/2009 13:45:30.005 -> 00

"fff"::	
Тысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 617  +  
6/15/2009 13:45:30.0005 -> 000

"ffff"::	
Десятитысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175 -> 6175  +  
6/15/2009 13:45:30.00005 -> 0000

"fffff"::	
Стотысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.61754 -> 61754  +  
6/15/2009 13:45:30.000005 -> 00000

"ffffff"::	
Миллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617542 -> 617542  +  
6/15/2009 13:45:30.0000005 -> 000000

"дсссссс"::	
Десятимиллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175425 -> 6175425  +  
6/15/2009 13:45:30.0001150 -> 0001150

"F"::	
Если ненулевое значение, то десятые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 6  +  
6/15/2009 13:45:30.050 -> (нет вывода)

"FF"::	
Если ненулевое значение, то сотые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 61  +  
6/15/2009 13:45:30.005 -> (нет вывода)

"FFF"::	
Если ненулевое значение, то тысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 617  +  
6/15/2009 13:45:30.0005 -> (нет вывода)

"FFFF"::	
Если ненулевое значение, то десятитысячные доли секунды в значении даты и времени.  +  
6/1/2009 13:45:30.5275 -> 5275  +  
6/15/2009 13:45:30.00005 -> (нет вывода)

"FFFFF"::	
Если ненулевое значение, то стотысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.61754 -> 61754  +  
6/15/2009 13:45:30.000005 -> (нет вывода)

"FFFFFF"::	
Если ненулевое значение, то миллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617542 -> 617542  +  
6/15/2009 13:45:30.0000005 -> (нет вывода)

"FFFFFFF"::	
Если ненулевое значение, то десятимиллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175425 -> 6175425  +  
6/15/2009 13:45:30.0001150 -> 000115

"g", "gg"::	
Период или эра.  +  
6/15/2009 1:45:30 PM -> A.D.

"h"::
Час в 12-часовом формате от 1 до 12.  +  
6/15/2009 1:45:30 AM -> 1  +  
6/15/2009 1:45:30 PM -> 1

"hh"::	
Час в 12-часовом формате от 01 до 12.  +  
6/15/2009 1:45:30 AM -> 01  +  
6/15/2009 1:45:30 PM -> 01

"H"::	
Час в 24-часовом формате от 0 до 23.  +  
6/15/2009 1:45:30 AM -> 1  +  
6/15/2009 1:45:30 PM -> 13

"HH"::	
Час в 24-часовом формате от 00 до 23.  +  
6/15/2009 1:45:30 AM -> 01  +  
6/15/2009 1:45:30 PM -> 13

"K"::	
Данные о часовом поясе.  +  
6/15/2009 1:45:30 PM, Kind Unspecified ->  +   
6/15/2009 1:45:30 PM, Kind Utc -> Z  +  
6/15/2009 1:45:30 PM, Kind Local -> -07:00

"m"::	
Минуты, в диапазоне от "0" до "59".  +  
6/15/2009 1:09:30 AM -> 9  +  
6/15/2009 1:09:30 PM -> 9

"mm"::	
Минуты, в диапазоне от 00 до 59.  +  
6/15/2009 1:09:30 AM -> 09  +  
6/15/2009 1:09:30 PM -> 09

"M"::	
Месяц, в диапазоне от 1 до 12.  +  
6/15/2009 1:45:30 PM -> 6

"MM"::	
Месяц, в диапазоне от 01 до 12.  +  
6/15/2009 1:45:30 PM -> 06

"MMM"::	
Сокращенное название месяца.  +   
6/15/2009 1:45:30 PM -> Jun (en-US)  +  
6/15/2009 1:45:30 PM -> juin (fr-FR)  +  
6/15/2009 1:45:30 PM -> Jun (zu-ZA)

"MMMM"::	
Полное название месяца.  +  
6/15/2009 1:45:30 PM -> June (en-US)  +  
6/15/2009 1:45:30 PM -> juni (da-DK)  +  
6/15/2009 1:45:30 PM -> uJuni (zu-ZA)

"s"::	
Секунды, в диапазоне от 0 до 59.  +  
6/15/2009 1:45:09 PM -> 9

"ss"::	
Секунды, в диапазоне от 00 до 59.  +  
6/15/2009 1:45:09 PM -> 09

"t"::	
Первый символ указателя AM/PM (до полудня/после полудня).  +  
6/15/2009 1:45:30 PM -> P (en-US)  +  
6/15/2009 1:45:30 PM -> (fr-FR)

"tt"::	
Указатель AM/PM (до полудня/после полудня).  +  
6/15/2009 1:45:30 PM -> PM (en-US)  +  
6/15/2009 1:45:30 PM -> (fr-FR)

"y"::	
Год, в диапазоне от 0 до 99.  +  
1/1/0001 12:00:00 AM -> 1  +  
1/1/0900 12:00:00 AM -> 0  +  
1/1/1900 12:00:00 AM -> 0  +  
6/15/2009 1:45:30 PM -> 9

"yy"::	
Год, в диапазоне от 00 до 99.  +  
1/1/0001 12:00:00 AM -> 01  +  
1/1/0900 12:00:00 AM -> 00  +  
1/1/1900 12:00:00 AM -> 00  +  
6/15/2009 1:45:30 PM -> 09

"yyy"::	
Год в виде как минимум трех цифр.  +  
1/1/0001 12:00:00 AM -> 001  +  
1/1/0900 12:00:00 AM -> 900  +  
1/1/1900 12:00:00 AM -> 1900  +  
6/15/2009 1:45:30 PM -> 2009

"yyyy"::	
Год в виде четырехзначного числа.  +  
1/1/0001 12:00:00 AM -> 0001  +  
1/1/0900 12:00:00 AM -> 0900  +  
1/1/1900 12:00:00 AM -> 1900  +  
6/15/2009 1:45:30 PM -> 2009

"yyyyy"::	
Год в виде пятизначного числа.  +  
1/1/0001 12:00:00 AM -> 00001  +  
6/15/2009 1:45:30 PM -> 02009

"z"::
Часовой сдвиг от времени в формате UTC (универсального времени), без нулей в начале.  +  
6/15/2009 1:45:30 PM -07:00 -> -7

"zz"::	
Часовой сдвиг от времени в формате UTC (универсального времени) с нулями в начале для значений из одной цифры.  +  
6/15/2009 1:45:30 PM -07:00 -> -07

"zzz"::	
Сдвиг в часах и минутах от времени в формате UTC (универсального времени).  +  
6/15/2009 1:45:30 PM -07:00 -> -07:00