:lang: ru

FNRouter 0.1.9
==============

// File router

Консольная утилита по перекладыванию файлов по каталогам и отправке на почту.

Работает на Windows 2000/XP/Vista/7. Установка не требуется. 

Требуется установленный http://www.microsoft.com/downloads/ru-ru/details.aspx?displaylang=ru&FamilyID=9cfb2d51-5ff4-4491-b0e5-b386f32c0992[.NET framework] версии 2.0 или выше

Распространяется по лицензии http://www.gnu.org/licenses/gpl-3.0.html[GNU GPL 3]

[red]#ВАЖНО!!! ВЫ ИСПОЛЬЗУЕТЕ ДАННЫЙ ПРОГРАММНЫЙ ПРОДУКТ НА СВОЙ СТРАХ И РИСК!!!#

*Автор заранее слагает с себя ответственность за весь возможный ущерб, причиненный программой.*

*This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.*

Описание
--------
Это консольная утилита, позволяет автоматизировать процесс раскладывания файлов по каталогам и отправке их на почту.

Настраивается через файл с правилами (по умолчанию fnrouter.ini) (кодировка win1251)

Параметры запуска: 

------------------------
fnrouter.exe [-cfile:Имя_файла_с_правилами] -rule:имя_правила [-check]
------------------------

Где имя_правила: имя правила для обработки

Если имя файла с правилами не указано используется fnrouter.ini

-check Проверить переменные в файле с правилами. Проверяет, что все переменные можно заменить на значения. 
Имя правила указывать при этом не нужно.

Одновременный запуск одного и того же правила блокируется (разные могут исполнятся одновременно).

Формат файла правил
-------------------

Любая строка после символа  # (решетка) - считается коментарием и не обрабатвается

Файл состоит из секций 
----------------------------
[Имя_секции1]
...
[Имя_секции2]
...
[Имя_секции3]
...
----------------------------

Служебные секции
----------------

[Mail] Настройки почтового сервера для рассылки сообщений
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mailsrv::
	Имя или адрес почтового сервера
mailfrom::
	Адрес отправителя
mailport::
	Номер порта сервера, можно не указывать
mailuser::
	Имя пользователя
mailpass::
	Пароль
MailToErrors::
	Адрес для отсылки сообщений об ошибках в копировании и перемещении файлов. Если пуст, сообщения не высылаются
	
Тоже самое можно задать используя параметры:
----------------------------
mailsrv=почтовый_сервер; mailfrom=адрес отправителя; mailport=номер_порта; mailuser=имя пользователя;  mailpass=пароль; 
----------------------------

Такую строку можно так же расположить в любом месте файла, она начнет действовать для правил расположенных ниже его и перекроет настройки секции [Mail]

[Vars] Переменные
~~~~~~~~~~~~~~~~~

Здесь можно задать переменные, для подстановки в параметры правил

----------------------------
Имя_переменной=значение
----------------------------

Имена одних переменных можно подставлять в значения других. Порядок указания их файле при этом не важен.
Например:

----------------------------
[Vars]
Disk=E:\
Path=Folder\
File=pismo.txt
FullPath=%Disk%%Path%%File%
----------------------------

----------------------------
%FullPath% станет строкой E:\Folder\pismo.txt
----------------------------

Дополнительно можно использовать переменные заданные программой (см. <<Pril1,приложение>>): имя компьютера, имя пользователя, специальные каталоги, дата и т.д.

Так же возможно использование переменных среды. Например %ComSpec% заменится на полный путь запуска файла cmd.exe.

Значения переменных можно использовать в значениях любых параметров, заключив имя переменной в проценты (%).

.Пример
-------------------------------------------------
[Mail]
...
[Vars]
BackupDir=d:\temp\backup\%yyMMdd%
Adr=me@mail.com
InDir=d:\temp\0
NeedAct=Move
;NeedAct=Delete
[Test]
# Строка с переменными
act=%NeedAct%;  s=%InDir%\*.rar; d=d:\temp\Arh; 

-------------------------------------------------

Правила
-------

Остальные секции - это наборы правил по обработке файлов
Имя секции - это название правила.

Каждая строка секции задает одно действие и записывается в виде:

-----------------------
Имя_параметра1=значение_параметра1; Имя_параметра2=значение_параметра2; Имя_параметра3=значение_параметра3; ...
-----------------------

Точка с запятой (;) обязательна и обозначает окончание параметра.

Параметры правила
~~~~~~~~~~~~~~~~~

Rule::
  Не обязателен. Имя правила. Перекроет значение имени секции. Сохранен для совместимости. Лучше использовать секции для имен правил.
  Может быть одинаковым для нескольких строчек. При запуске программы указывается имя правила, строчки имеющие это имя будут последовательно обрабатываться сверху вниз. Каждое правило может состоять из нескольких строк. Действия при этом выполняются сверху вниз
Act::
	Обязателен. Действие выполняемое с файлами.
S::
	Обязателен. Полный путь к каталогу с обрабатываемыми файлами. Если не используется параметр Inc, то должен содержать маску (только одну). Подкаталоги не обрабатываются. Если используется параметр Inc, маска не указывается. Может содержать переменные даты времени/имен файлов
Inc::
	Не обязательный параметр. Маски включаемых файлов для обработки, разделяются запятыми (,).
Exclude::
	Не обязательный параметр. Маски исключаемых из обработки файлов, разделяются запятыми (,).
Contain::
	Не обязательный параметр. Строка которую должен содержать файл. Сравнение регистрозависимое. Можно указывать несколько значений через знак |. Будет выбран файл содержащий любую из этих строк.
NotContain::
	Не обязательный параметр. Строка которую НЕ должен содержать файл. Сравнение регистрозависимое. Можно указывать несколько значений через знак |. Будет выбран файл НЕ содержащий ни одну из этих строк.
D::
	Полный путь к каталогу назанчения. Используется не во всех действиях. Может содержать переменные даты времени/имен файлов.
Cmd::
	Файл для запуска. Используется в командах запуска внешнего файла
Args::
	Не обязателен. Аргументы для команды Cmd. Если содержат переменные %FileName% и т.д. команда запускается для каждого файла в отдельности. Если не содержат, то запускается один раз на все файлы.
Subj::
	Тема письма. Для правил отправки почты. Может содержать переменные даты времени/имен файлов.
Text::
	Текст письма. Для правил отправки почты. Может содержать переменные даты времени/имен файлов.

Действия
~~~~~~~~

Действиями (Act) могут быть:

Copy::
 Копировать файлы
Move::
 Переместить файлы
Delete::
 Удалить файлы
Send::
 Отправить файлы по почте (одно письмо один файл)
SendMsg::
 отправить уведомление на почту о файлах, без отправки самого файла (одно письмо на все файлы)
RunWait::
 Запустить внешнюю программу с ожиданием
RunNoWait::
 Запустиь внешнюю программу без ожидания
UnRar::
 Распаковать архив rar
UnArj::
 Распаковать архив arj
UnCab::
 Распаковать архив cab
Nothing::
 Ничего не делать. Используется для создания списка файлов при множественной обработке.

 
Отбор файлов для обработки
~~~~~~~~~~~~~~~~~~~~~~~~~~
 
Действие выполняется над файлами попадающими в условия отбора. Если необходимо отобрать файлы только по одной маске, то достаточно указать полный путь к каталогу и маску в параметре s

Например:

---------------------------------
[Test]
act=Copy;  s=d:\temp\0\*; d=d:\temp\1; 
---------------------------------
Скопирует все файлы из d:\temp\0\ в d:\temp\1

Возможно указание нескольких масок файлов для включения в обработку параметром Inc. 
Маски разделяютя запятой ",". При этом в параметре s необходимо указывать только полный путь к каталогу.

Например:

---------------------------------
[Test]
act=Copy;  s=d:\temp\0; d=d:\temp\1; Inc=*.rar,*.zip; 
---------------------------------
Скопирует все файлы rar и zip из d:\temp\0\ в d:\temp\1

Возможно указание масок файлов для исключения из обработки параметром Exclude. 
Маски разделяютя запятой ","

Например:

---------------------------------
[Test]
act=Copy;  s=d:\temp\0; d=d:\temp\1; Inc=*.rar,*.zip; Exclude=temp.rar,temp.zip;
---------------------------------

Скопирует все файлы rar и zip кроме temp.rar и temp.zip из d:\temp\0\ в d:\temp\1

Дополнительно можно указывать, что файл должен содержать заданную строку параметром contain=строка; 
(Сравнение регистрозависимое)

В имени каталогов можно указывать дату/время в %. Например %yyMMdd% - преобразуется в текущую дату. 
Т.е. что-то вроде d:\temp\%yyMMdd%\1\*


Несколько операций над файлами
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Если необходимо произвести несколько действий с файлами, распологайте строчки подряд.
В следующих строках указывайте источник S=$;

Если в параметре S указано значение $ для строки, то обрабатываются файлы заданные в предыдущем правиле, с заполненным параметром S.
При этом составляется список файлов для обработки и в последующем обрабатывается только этот список. Если в процессе обработки в каталоге появятся новые файлы, они обработаны не будут.

Файлы можно фильтровать дополнительными значениями параметров Inc, Exclude, Contain, NotContain. Но учитывайте, что фильтры применятются к списку файлов заданным строчкой с заполненным S.
Если необходимо, можно использовать действие Nothing для первоначального создания списка файлов, и потом его фильтровать.


Примеры

.Файлы копируются в один каталог, затем переносятся в другой
---------------------------------
[Test]
act=Copy;  s=d:\temp\0\*; d=d:\temp\1; 
act=Move;  s=$;	          d=d:\temp\backup\%yyMMdd%; 
---------------------------------
При этом если после выполнения 1-ой строчки в каталоге d:\temp\0\ появится файл, он не будет обработан 2-ой строчкой.


.Фильтр по расширению и содержимому
---------------------------------
[Test]
# Задается список обрабатываемых файлов, все они копируются в all
act=Copy;  s=d:\temp\0\*; d=d:\temp\1\all; 
# Из заданного списка копируются только текстовые файлы
act=Copy;  s=$; inc=*.txt; d=d:\temp\1\txt; 
# Копируются файлы log содержащие текст "ошибка"
act=Copy;  s=$; inc=*.log; contain=ошибка; d=d:\temp\1\txt; 
# Все файлы первой строки переносятся в backup
act=Move;  s=$; d=d:\temp\backup\%yyMMdd%; 
---------------------------------

.Nothing
---------------------------------
[Test]
# Задается список обрабатываемых файлов, с ними ничего не происходит
# Если вам ничего первоначально с файлами делать не нужно указывайте Nothing
act=Nothing;  s=d:\temp\0\*; 
# Из заданного списка копируются только текстовые файлы
act=Copy;  s=$; inc=*.txt; d=d:\temp\1\txt; 
# Копируются файлы log содержащие текст "ошибка" или "предупреждение"
act=Copy;  s=$; inc=*.log; contain=ошибка|предупреждение; d=d:\temp\1\txt; 
# Все файлы первой строки переносятся в backup
act=Move;  s=$; d=d:\temp\backup\%yyMMdd%; 
---------------------------------

.Не верное правило без Nothing
---------------------------------
[Test]
# Первоначально задаются только txt файлы.
act=Copy;  s=d:\temp\0; Inc=*.txt; d=d:\temp\1\txt; 
# Файлы log скопированы не будут, т.к. в первоначальном фильтре только txt
act=Copy;  s=$; inc=*.log; contain=ошибка|предупреждение; d=d:\temp\1\txt; 
# файлы первой строки, т.е. только txt, переносятся в backup
act=Move;  s=$; d=d:\temp\backup\%yyMMdd%; 
---------------------------------


Отправка писем
--------------

.Отправка файла на почту:
-------------------------------
act=Send;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------
В теме и тексте можно использовать Переменные вроде  %FileName% - имя файла, %FullFileName% - полное имя файла, см. ниже

.Отправка уведомления о файлах на почту:

-------------------------------
act=SendMsg;   s=d:\test\in\*.*; to=адреса получателей через запятую; subj=Тема письма; text=Текст письма; 
-------------------------------

Так же можно использовать переменные для текущей даты/времени (в именах каталогов и письмах). См. приложение.

Распаковка архивов
------------------

.Распаковки Rar
-------------------------------
act=UnRar;  s=d:\test\in\*.rar; d=E:\test\%FileWithoutExt%; 
-------------------------------
%FileWithoutExt% - создаст каталог с именем архива (без расширения) + 
Rar.exe - должен находится в путях %Path% или в каталоге с программой.

.Распаковка Arj
-------------------------------
act=UnArj;  s=d:\test\in\*.arj; d=E:\test\%yyMMdd%; 
-------------------------------
arj32.exe - должен находится в путях %Path% или в каталоге с программой.

.Распаковка Cab
-------------------------------
act=UnCab;  s=d:\test\in\*; d=E:\test\%yyMMdd%; 
-------------------------------
expand.exe - должен находится в путях %Path% или в каталоге с программой. Обычно находится в %WinDir%\System32

Запуск внешних программ
-----------------------

Используйте действия RunWait и RunNoWait

Для RunWait и RunNoWait испльзуется параметр cmd=имя_запускаемого_файла.

Файл запускается если существуют файлы попадающие в критерии отбора.

.Запуск программы с ожиданием
----------------------------
act=RunWait; s=d:\temp\*; cmd=c:\balalaika.exe; 
----------------------------

Запустится c:\balalaika.exe если в каталоге d:\temp есть файлы

Возможно указание параметров запуска через args. Если параметры содержат переменные %FileName% и т.д. команда запускается для каждого файла в отдельности. Если не содержат, то запускается один раз на все файлы.

Например:

.Запуск программы с ожиданием для каждого файла
----------------------------
act=RunWait; s=d:\temp\*.txt; cmd=c:\Utils\convert.exe; args=-c %FullFileName%
----------------------------
Для каждого txt файла из d:\temp будет выполнен запуск
c:\Utils\convert.exe -с Полное_имя_файла


Протоколы работы
----------------

Во время работы ведутся логи. Запись идет в подкаталог Log программы. Файлы логов имеют имя ГГММДД-имя_правила.log - каждый файл соответсвует одному дню одного правила.

При указании адреса в параметре MailToErrors в секции [Mail] на данный адрес будет производится отсылка сообщений об ошибках в копировании и перемещении файлов.

Контакты 
--------

Вопросы, предложения, замечания принимаются по адресу atsave@narod.ru  +  
Сайт программы: http://atsave.narod.ru

[[Pril1]]
Приложение: переменные
----------------------

Проверить правильность задания переменных можно командой

------------------------
 fnrouter.exe -check
------------------------

Переменные имен обрабатываемых файлов
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Для указания обрабатываемых файлов *в теме, тексте письма, параметрах запуска* можно использовать следующие переменные:

%ListFileName%::
 список коротких имен файлов (только для почты, список через запятую)
%ListFullFileName%::
 список длинных имен файлов (только для почты, список через запятую)
%FullFileName%::
 полное имя файла
%FileName%::
 короткое имя файла
%FileWithoutExt%::
 только имя файла без расширения
%ExtFile%::
 расширение имени файла

Переменные задаваемые программой
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

%ComputerName%::
	Имя компьютера на котором запущена программа
%MachineName%::
	Синоним %ComputerName%
%UserName%::
	Имя пользователя под которым запущена программа
%NewLine%::
	Символы перехода на другую строку

Переменные специальных каталогов
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	
ApplicationData:: Каталог, выполняющий функции общего хранилища для данных приложения текущего перемещающегося пользователя.  
 CommonApplicationData:: Каталог, выполняющий функции общего хранилища для данных приложения, используемого всеми пользователями.  
 LocalApplicationData:: Каталог, служащий общим хранилищем данных приложения, используемых текущим пользователем, который не перемещается.  
 Cookies:: Каталог, служащий общим хранилищем интернет-файлов cookie.  
 Desktop:: Логический рабочий стол, а не физическое местоположение файлов системы.  
 Favorites:: Каталог, служащий общим хранилищем для избранных элементов пользователя.  
 History:: Каталог, служащий общим хранилищем элементов журнала Интернета.  
 InternetCache:: Каталог, служащий общим хранилищем временных файлов Интернета.  
 Programs:: Каталог, содержащий группы программ пользователя.  
 MyComputer:: Папка "Мой компьютер".  
 MyMusic:: Папка "Моя музыка".  
 MyPictures:: Папка "Мои рисунки".  
 Recent:: Каталог, содержащий недавно использовавшиеся документы.  
 SendTo:: Каталог, содержащий пункты меню "Отправить".  
 StartMenu:: Каталог, содержащий пункты меню "Пуск".  
 Startup:: Каталог, соответствующий группе программ пользователя "Автозагрузка".  
 System:: Каталог System.  
 Templates:: Каталог, служащий общим хранилищем для шаблонов документов.  
 DesktopDirectory:: Каталог, используемый для физического хранения файловых объектов рабочего стола.  
 Personal:: Каталог, служащий общим хранилищем для документов.  
 MyDocuments:: Папка "Мои документы".  
 ProgramFiles:: Каталог файлов программ.  
 CommonProgramFiles:: Каталог для компонентов, общих для приложений.  

	
	
Переменные даты/времени
~~~~~~~~~~~~~~~~~~~~~~~
	
Если необходимо указать несколько параметров, заключайте каждый в %
Например: %dd%%MM%%yy%.
Используйте fnrouter.exe -check для проверки правильности указания параметров

"d"::
 День месяца, в диапазоне от 1 до 31.  +   
 6/1/2009 1:45:30 PM -> 1  +  
 6/15/2009 1:45:30 PM -> 15

"dd"::	
 День месяца, в диапазоне от 01 до 31.  +  
 6/1/2009 1:45:30 PM -> 01  +  
 6/15/2009 1:45:30 PM -> 15

"ddd"::
Сокращенное название дня недели.  +  
6/15/2009 1:45:30 PM -> Mon (en-US)  +  
6/15/2009 1:45:30 PM -> Пн (ru-RU)  +  
6/15/2009 1:45:30 PM -> lun. (fr-FR)

"dddd"::	
Полное название дня недели.  +  
6/15/2009 1:45:30 PM -> Monday (en-US)  +  
6/15/2009 1:45:30 PM -> понедельник (ru-RU)  +  
6/15/2009 1:45:30 PM -> lundi (fr-FR)

"f"::	
Десятые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 6  +  
6/15/2009 13:45:30.050 -> 0 

"ff"::	
Сотые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 61  +  
6/15/2009 13:45:30.005 -> 00

"fff"::	
Тысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 617  +  
6/15/2009 13:45:30.0005 -> 000

"ffff"::	
Десятитысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175 -> 6175  +  
6/15/2009 13:45:30.00005 -> 0000

"fffff"::	
Стотысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.61754 -> 61754  +  
6/15/2009 13:45:30.000005 -> 00000

"ffffff"::	
Миллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617542 -> 617542  +  
6/15/2009 13:45:30.0000005 -> 000000

"дсссссс"::	
Десятимиллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175425 -> 6175425  +  
6/15/2009 13:45:30.0001150 -> 0001150

"F"::	
Если ненулевое значение, то десятые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 6  +  
6/15/2009 13:45:30.050 -> (нет вывода)

"FF"::	
Если ненулевое значение, то сотые доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 61  +  
6/15/2009 13:45:30.005 -> (нет вывода)

"FFF"::	
Если ненулевое значение, то тысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617 -> 617  +  
6/15/2009 13:45:30.0005 -> (нет вывода)

"FFFF"::	
Если ненулевое значение, то десятитысячные доли секунды в значении даты и времени.  +  
6/1/2009 13:45:30.5275 -> 5275  +  
6/15/2009 13:45:30.00005 -> (нет вывода)

"FFFFF"::	
Если ненулевое значение, то стотысячные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.61754 -> 61754  +  
6/15/2009 13:45:30.000005 -> (нет вывода)

"FFFFFF"::	
Если ненулевое значение, то миллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.617542 -> 617542  +  
6/15/2009 13:45:30.0000005 -> (нет вывода)

"FFFFFFF"::	
Если ненулевое значение, то десятимиллионные доли секунды в значении даты и времени.  +  
6/15/2009 13:45:30.6175425 -> 6175425  +  
6/15/2009 13:45:30.0001150 -> 000115

"g", "gg"::	
Период или эра.  +  
6/15/2009 1:45:30 PM -> A.D.

"h"::
Час в 12-часовом формате от 1 до 12.  +  
6/15/2009 1:45:30 AM -> 1  +  
6/15/2009 1:45:30 PM -> 1

"hh"::	
Час в 12-часовом формате от 01 до 12.  +  
6/15/2009 1:45:30 AM -> 01  +  
6/15/2009 1:45:30 PM -> 01

"H"::	
Час в 24-часовом формате от 0 до 23.  +  
6/15/2009 1:45:30 AM -> 1  +  
6/15/2009 1:45:30 PM -> 13

"HH"::	
Час в 24-часовом формате от 00 до 23.  +  
6/15/2009 1:45:30 AM -> 01  +  
6/15/2009 1:45:30 PM -> 13

"K"::	
Данные о часовом поясе.  +  
6/15/2009 1:45:30 PM, Kind Unspecified ->  +   
6/15/2009 1:45:30 PM, Kind Utc -> Z  +  
6/15/2009 1:45:30 PM, Kind Local -> -07:00

"m"::	
Минуты, в диапазоне от "0" до "59".  +  
6/15/2009 1:09:30 AM -> 9  +  
6/15/2009 1:09:30 PM -> 9

"mm"::	
Минуты, в диапазоне от 00 до 59.  +  
6/15/2009 1:09:30 AM -> 09  +  
6/15/2009 1:09:30 PM -> 09

"M"::	
Месяц, в диапазоне от 1 до 12.  +  
6/15/2009 1:45:30 PM -> 6

"MM"::	
Месяц, в диапазоне от 01 до 12.  +  
6/15/2009 1:45:30 PM -> 06

"MMM"::	
Сокращенное название месяца.  +   
6/15/2009 1:45:30 PM -> Jun (en-US)  +  
6/15/2009 1:45:30 PM -> juin (fr-FR)  +  
6/15/2009 1:45:30 PM -> Jun (zu-ZA)

"MMMM"::	
Полное название месяца.  +  
6/15/2009 1:45:30 PM -> June (en-US)  +  
6/15/2009 1:45:30 PM -> juni (da-DK)  +  
6/15/2009 1:45:30 PM -> uJuni (zu-ZA)

"s"::	
Секунды, в диапазоне от 0 до 59.  +  
6/15/2009 1:45:09 PM -> 9

"ss"::	
Секунды, в диапазоне от 00 до 59.  +  
6/15/2009 1:45:09 PM -> 09

"t"::	
Первый символ указателя AM/PM (до полудня/после полудня).  +  
6/15/2009 1:45:30 PM -> P (en-US)  +  
6/15/2009 1:45:30 PM -> (fr-FR)

"tt"::	
Указатель AM/PM (до полудня/после полудня).  +  
6/15/2009 1:45:30 PM -> PM (en-US)  +  
6/15/2009 1:45:30 PM -> (fr-FR)

"y"::	
Год, в диапазоне от 0 до 99.  +  
1/1/0001 12:00:00 AM -> 1  +  
1/1/0900 12:00:00 AM -> 0  +  
1/1/1900 12:00:00 AM -> 0  +  
6/15/2009 1:45:30 PM -> 9

"yy"::	
Год, в диапазоне от 00 до 99.  +  
1/1/0001 12:00:00 AM -> 01  +  
1/1/0900 12:00:00 AM -> 00  +  
1/1/1900 12:00:00 AM -> 00  +  
6/15/2009 1:45:30 PM -> 09

"yyy"::	
Год в виде как минимум трех цифр.  +  
1/1/0001 12:00:00 AM -> 001  +  
1/1/0900 12:00:00 AM -> 900  +  
1/1/1900 12:00:00 AM -> 1900  +  
6/15/2009 1:45:30 PM -> 2009

"yyyy"::	
Год в виде четырехзначного числа.  +  
1/1/0001 12:00:00 AM -> 0001  +  
1/1/0900 12:00:00 AM -> 0900  +  
1/1/1900 12:00:00 AM -> 1900  +  
6/15/2009 1:45:30 PM -> 2009

"yyyyy"::	
Год в виде пятизначного числа.  +  
1/1/0001 12:00:00 AM -> 00001  +  
6/15/2009 1:45:30 PM -> 02009

"z"::
Часовой сдвиг от времени в формате UTC (универсального времени), без нулей в начале.  +  
6/15/2009 1:45:30 PM -07:00 -> -7

"zz"::	
Часовой сдвиг от времени в формате UTC (универсального времени) с нулями в начале для значений из одной цифры.  +  
6/15/2009 1:45:30 PM -07:00 -> -07

"zzz"::	
Сдвиг в часах и минутах от времени в формате UTC (универсального времени).  +  
6/15/2009 1:45:30 PM -07:00 -> -07:00